name: secman_parking
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  camera: ^0.9.4+5
  cloud_firestore: ^3.1.4
  equatable: ^2.0.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.2.4
  fluttertoast: ^8.0.8
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  json_annotation: ^4.3.0
  nfc_manager: ^3.1.1
  path_provider: ^2.0.8
  reactive_forms: ^11.0.0
  reactive_pin_code_fields: ^0.1.0
  shared_preferences: ^2.0.11
  table_calendar: ^3.0.5

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
